version: '3.5'

services:
  # container with docker instance
  jenkins-docker:
    privileged: true
    networks:
      jenkins:
        aliases: 
          - docker

    image: docker:dind
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client
  jenkins-main:
    networks:
      - jenkins
    build:
      context: ./jenkins
    environment:
      JENKINS_ADMIN_ID: admin 
      JENKINS_ADMIN_PASSWORD: "@ART3M1S"
      DOCKER_TLS_VERIFY: 1
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    ports:
      - 8080:8080
      - 50000:50000
  
volumes:
  jenkins-data:
  jenkins-docker-certs:
networks:
  jenkins: