# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_speakers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='twitter_username',
            field=models.CharField(blank=True, help_text='Your Twitter account', max_length=15),
        ),
    ]
