# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-17 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='name',
            field=models.CharField(default='', editable=False, max_length=100),
            preserve_default=False,
        ),
    ]
